; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

; Generated by VC++ for Common Language Runtime
.file "D:\Class\6.0\TTmp\kclrcall\pch.cpp"
.global	___@@_PchSym_@00@UxozhhUGOAUggnkUpxoixzooUwvyftUkxsOlyq@4B2008FD98C1DD4
	.bss
	.comdat	any, ___@@_PchSym_@00@UxozhhUGOAUggnkUpxoixzooUwvyftUkxsOlyq@4B2008FD98C1DD4
.local	___@@_PchSym_@00@UxozhhUGOAUggnkUpxoixzooUwvyftUkxsOlyq@4B2008FD98C1DD4,4
