; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

	TITLE	D:\Class\6.0\TTmp\TTx\KSTL.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__6C672F41_vcruntime_new@h DB 01H
__23AD7809_corecrt_stdio_config@h DB 01H
__DD74D44A_corecrt_wstdio@h DB 01H
__4B3541EE_stdio@h DB 01H
__82CA083D_corecrt_memcpy_s@h DB 01H
__F8BB3D43_corecrt_memory@h DB 01H
__61E6ED1F_corecrt_wstring@h DB 01H
__B0CBCB7B_string@h DB 01H
__990BA27D_corecrt_wconio@h DB 01H
__D837D19F_corecrt_wio@h DB 01H
__FE12CC83_corecrt_wtime@h DB 01H
__01EE68DC_stat@h DB 01H
__B513A213_wchar@h DB 01H
__E410F33D_corecrt_math@h DB 01H
__36B85FDF_stdlib@h DB 01H
__AA918B9C_cstdlib DB 01H
__1A71149F_limits DB 01H
__45E68E76_type_traits DB 01H
__A2957829_malloc@h DB 01H
__2DC1B543_vcruntime_exception@h DB 01H
__A3920001_exception DB 01H
__76C3EE5D_xutility DB 01H
__A7902F0C_xmemory0 DB 01H
__83DAEB48_xstring DB 01H
__941D13D0_ctype@h DB 01H
__D20C9E8D_string DB 01H
__8525548B_KSTL@h DB 01H
__C71EB663_KSTL@cpp DB 01H
__9D9C0E17_utility DB 01H
__6A839905_xstddef DB 01H
msvcjmc	ENDS
PUBLIC	??0KSTL@@QAE@XZ					; KSTL::KSTL
PUBLIC	??1KSTL@@QAE@XZ					; KSTL::~KSTL
PUBLIC	__JustMyCode_Default
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	___CxxFrameHandler3:PROC
EXTRN	___security_cookie:DWORD
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__ehfuncinfo$??1KSTL@@QAE@XZ DD 019930522H
	DD	00H
	DD	00H
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	05H
xdata$x	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File D:\Class\6.0\TTmp\TTx\KSTL.cpp
;	COMDAT ??1KSTL@@QAE@XZ
_TEXT	SEGMENT
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
??1KSTL@@QAE@XZ PROC					; KSTL::~KSTL, COMDAT
; _this$ = ecx

; 11   : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??1KSTL@@QAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, OFFSET __C71EB663_KSTL@cpp
	call	@__CheckForDebuggerJustMyCode@4

; 12   : }

	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__ehhandler$??1KSTL@@QAE@XZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-220]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??1KSTL@@QAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??1KSTL@@QAE@XZ ENDP					; KSTL::~KSTL
; Function compile flags: /Odtp /RTCsu /ZI
; File D:\Class\6.0\TTmp\TTx\KSTL.cpp
;	COMDAT ??0KSTL@@QAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??0KSTL@@QAE@XZ PROC					; KSTL::KSTL, COMDAT
; _this$ = ecx

; 6    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, OFFSET __C71EB663_KSTL@cpp
	call	@__CheckForDebuggerJustMyCode@4

; 7    : }

	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??0KSTL@@QAE@XZ ENDP					; KSTL::KSTL
_TEXT	ENDS
END
